# Language: English
# Add this file to langs/ folder — the app will pick it up automatically

LANG_NAME = "English"
LANG_CODE = "en"

T = {
    "app_name": "CraftControl",
    "app_ready": "Ready. Select a server and press Start.",

    "tab_console": "⬛ Console",
    "tab_servers": "🖥  Servers",
    "tab_players": "👥 Players",
    "tab_kernels": "⬇ Kernels & Mods",
    "tab_props":   "⚙ Properties",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Settings",

    "toolbar_open_dir":  "📁 Open Folder",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Server Online",
    "status_offline":    "⚫ Server Offline",

    "console_placeholder": "Enter command... (e.g. /say Hello)",
    "console_send":        "▶ Send",
    "console_clear":       "🗑 Clear",
    "console_server_offline": "Server is not running",

    "servers_title":     "My Servers",
    "servers_add":       "+ Add",
    "servers_del":       "✕ Delete",
    "servers_save":      "💾 Save",
    "servers_start":     "▶ Start",
    "servers_stop":      "⏹ Stop",
    "servers_settings":  "Server Settings",
    "servers_name":      "Name:",
    "servers_jar":       "Jar file:",
    "servers_dir":       "Directory:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Port:",
    "servers_eula":      "Accept EULA",
    "servers_eula_btn":  "Create eula.txt",
    "servers_new_name":  "New server name:",
    "servers_del_confirm": "Remove this server from the list?",
    "servers_eula_done": "eula.txt created:",
    "servers_saved":     "Server saved:",
    "servers_no_jar":    "JAR file not found. Please set the correct path.",
    "servers_starting":  "Starting",
    "servers_stopped":   "Server stopped",
    "servers_select":    "Select a server",
    "servers_no_dir":    "Set the server directory first",
    "servers_rcon_group": "RCON (live player list)",
    "servers_rcon_host": "Host:",
    "servers_rcon_port": "RCON port:",
    "servers_rcon_pass": "RCON password:",
    "servers_rcon_hint": "Enable in server.properties: enable-rcon=true, rcon.password=...",
    "servers_api_group": "Custom Server API",
    "servers_api_url":   "API URL:",
    "servers_api_key":   "API key:",
    "servers_api_hint":  "REST API for server data. E.g.: http://localhost:8080",

    "players_nick":      "Player nickname...",
    "players_add":       "+ Add",
    "players_rank":      "Role",
    "players_status":    "Status",
    "players_ip":        "IP",
    "players_actions":   "Actions",
    "players_kick":      "⚡ Kick",
    "players_ban":       "🔨 Ban",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "Online",
    "players_offline":   "Offline",
    "players_refresh":   "🔄 Refresh",
    "players_added":     "Player added:",
    "players_server_offline": "Server offline. Command:",
    "players_rcon_error": "RCON error:",
    "players_api_error":  "API error:",

    "kernels_type":      "Type:",
    "kernels_fetch":     "🔍 Fetch list",
    "kernels_dest":      "Save folder...",
    "kernels_browse":    "📁 Browse",
    "kernels_download":  "⬇ Download kernel",
    "kernels_fetching":  "Fetching list...",
    "kernels_found":     "Found versions:",
    "kernels_none":      "No versions found",
    "kernels_saved":     "Kernel downloaded:",
    "kernels_select":    "Select a version from the list",
    "kernels_no_dest":   "Set save folder",
    "kernels_downloading": "Downloading...",
    "kernels_error":     "Download error:",
    "kernels_fetch_error": "Fetch error:",
    "kernels_fetch_start": "Fetching kernels:",

    "mods_title":        "Mods / Plugins / Datapacks",
    "mods_search_ph":    "Search... (name or slug)",
    "mods_search_btn":   "🔍 Search",
    "mods_source":       "Source:",
    "mods_type":         "Type:",
    "mods_server_dir":   "Server folder:",
    "mods_install":      "⬇ Install",
    "mods_open_folder":  "📁 Open folder",
    "mods_installing":   "Installing...",
    "mods_installed":    "Installed:",
    "mods_error":        "Error:",
    "mods_select":       "Select a mod from the list",
    "mods_no_dir":       "Set server folder",
    "mods_searching":    "Searching...",
    "mods_no_results":   "Nothing found",
    "mods_results":      "Results:",

    "props_load":        "📂 Load server.properties",
    "props_save":        "💾 Save",
    "props_saved":       "Saved:",
    "props_loaded":      "Loaded:",

    "wiki_articles":     "Articles",

    "settings_title":    "Settings",
    "settings_ui_group": "Interface",
    "settings_lang":     "Language:",
    "settings_theme":    "Theme:",
    "settings_theme_dark":  "Dark",
    "settings_theme_light": "Light",
    "settings_font_size":"Font size:",
    "settings_accent":   "Accent color:",
    "settings_accent_green":  "🟢 Green",
    "settings_accent_blue":   "🔵 Blue",
    "settings_accent_purple": "🟣 Purple",
    "settings_accent_orange": "🟠 Orange",
    "settings_java_group": "Java",
    "settings_java_path": "Java path:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Auto-detect",
    "settings_save":     "💾 Save Settings",
    "settings_saved":    "Settings saved!",
    "settings_restart":  "Some changes will take effect after restart.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Path to playit.exe:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Launch Playit",
    "settings_playit_site":   "🌐 Website",

    "dlg_ok":       "OK",
    "dlg_cancel":   "Cancel",
    "dlg_yes":      "Yes",
    "dlg_no":       "No",
    "dlg_warning":  "Warning",
    "dlg_error":    "Error",
    "dlg_confirm":  "Confirm",
    "dlg_input":    "Input",
    "dlg_exit":     "Server is still running. Stop and exit?",
    "dlg_del":      "Delete?",
    "dlg_del_article": "Delete this article?",
    "dlg_del_player":  "Remove player from list?",

    "browse":       "📁 Browse",
    "no_dir":       "Directory not set or doesn't exist",
}
