# Język: Polski
# Language: Polish
# Dodaj ten plik do folderu langs/ — aplikacja go automatycznie wykryje

LANG_NAME = "Polski"
LANG_CODE = "pl"

T = {
    "app_name": "CraftControl",
    "app_ready": "Gotowy. Wybierz serwer i naciśnij Start.",

    "tab_console": "⬛ Konsola",
    "tab_servers": "🖥  Serwery",
    "tab_players": "👥 Gracze",
    "tab_kernels": "⬇ Jądra i Mody",
    "tab_props":   "⚙ Properties",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Ustawienia",

    "toolbar_open_dir":  "📁 Otwórz folder",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Serwer online",
    "status_offline":    "⚫ Serwer offline",

    "console_placeholder": "Wpisz komendę... (np. /say Hello)",
    "console_send":        "▶ Wyślij",
    "console_clear":       "🗑 Wyczyść",
    "console_server_offline": "Serwer nie jest uruchomiony",

    "servers_title":     "Moje serwery",
    "servers_add":       "+ Dodaj",
    "servers_del":       "✕ Usuń",
    "servers_save":      "💾 Zapisz",
    "servers_start":     "▶ Uruchom",
    "servers_stop":      "⏹ Zatrzymaj",
    "servers_settings":  "Ustawienia serwera",
    "servers_name":      "Nazwa:",
    "servers_jar":       "Plik Jar:",
    "servers_dir":       "Katalog:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Port:",
    "servers_eula":      "Akceptuj EULA",
    "servers_eula_btn":  "Utwórz eula.txt",
    "servers_new_name":  "Nazwa nowego serwera:",
    "servers_del_confirm": "Usunąć ten serwer z listy?",
    "servers_eula_done": "eula.txt utworzony:",
    "servers_saved":     "Serwer zapisany:",
    "servers_no_jar":    "Plik JAR nie znaleziony.",
    "servers_starting":  "Uruchamianie",
    "servers_stopped":   "Serwer zatrzymany",
    "servers_select":    "Wybierz serwer",
    "servers_no_dir":    "Najpierw ustaw katalog serwera",
    "servers_rcon_group": "RCON (lista graczy online)",
    "servers_rcon_host": "Host:",
    "servers_rcon_port": "Port RCON:",
    "servers_rcon_pass": "Hasło RCON:",
    "servers_rcon_hint": "Włącz w server.properties: enable-rcon=true",
    "servers_api_group": "Własne API serwera",
    "servers_api_url":   "API URL:",
    "servers_api_key":   "Klucz API:",
    "servers_api_hint":  "REST API dla danych serwera. Np.: http://localhost:8080",

    "players_nick":      "Nick gracza...",
    "players_add":       "+ Dodaj",
    "players_rank":      "Rola",
    "players_status":    "Status",
    "players_ip":        "IP",
    "players_actions":   "Akcje",
    "players_kick":      "⚡ Kick",
    "players_ban":       "🔨 Ban",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "Online",
    "players_offline":   "Offline",
    "players_refresh":   "🔄 Odśwież",
    "players_added":     "Gracz dodany:",
    "players_server_offline": "Serwer offline. Komenda:",
    "players_rcon_error": "Błąd RCON:",
    "players_api_error":  "Błąd API:",

    "kernels_type":      "Typ:",
    "kernels_fetch":     "🔍 Pobierz listę",
    "kernels_dest":      "Folder zapisu...",
    "kernels_browse":    "📁 Wybierz",
    "kernels_download":  "⬇ Pobierz jądro",
    "kernels_fetching":  "Pobieranie listy...",
    "kernels_found":     "Znaleziono wersji:",
    "kernels_none":      "Nie znaleziono wersji",
    "kernels_saved":     "Jądro pobrane:",
    "kernels_select":    "Wybierz wersję z listy",
    "kernels_no_dest":   "Ustaw folder zapisu",
    "kernels_downloading": "Pobieranie...",
    "kernels_error":     "Błąd pobierania:",
    "kernels_fetch_error": "Błąd pobierania listy:",
    "kernels_fetch_start": "Pobieranie jąder:",

    "mods_title":        "Mody / Pluginy / Datapaki",
    "mods_search_ph":    "Szukaj... (nazwa lub slug)",
    "mods_search_btn":   "🔍 Szukaj",
    "mods_source":       "Źródło:",
    "mods_type":         "Typ:",
    "mods_server_dir":   "Folder serwera:",
    "mods_install":      "⬇ Zainstaluj",
    "mods_open_folder":  "📁 Otwórz folder",
    "mods_installing":   "Instalowanie...",
    "mods_installed":    "Zainstalowano:",
    "mods_error":        "Błąd:",
    "mods_select":       "Wybierz mod z listy",
    "mods_no_dir":       "Ustaw folder serwera",
    "mods_searching":    "Szukanie...",
    "mods_no_results":   "Nic nie znaleziono",
    "mods_results":      "Wyników:",

    "props_load":        "📂 Wczytaj server.properties",
    "props_save":        "💾 Zapisz",
    "props_saved":       "Zapisano:",
    "props_loaded":      "Wczytano:",

    "wiki_articles":     "Artykuły",

    "settings_title":    "Ustawienia",
    "settings_ui_group": "Interfejs",
    "settings_lang":     "Język:",
    "settings_theme":    "Motyw:",
    "settings_theme_dark":  "Ciemny",
    "settings_theme_light": "Jasny",
    "settings_font_size":"Rozmiar czcionki:",
    "settings_accent":   "Kolor akcentu:",
    "settings_accent_green":  "🟢 Zielony",
    "settings_accent_blue":   "🔵 Niebieski",
    "settings_accent_purple": "🟣 Fioletowy",
    "settings_accent_orange": "🟠 Pomarańczowy",
    "settings_java_group": "Java",
    "settings_java_path": "Ścieżka do Java:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Wykryj automatycznie",
    "settings_save":     "💾 Zapisz ustawienia",
    "settings_saved":    "Ustawienia zapisane!",
    "settings_restart":  "Niektóre zmiany wejdą w życie po restarcie.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Ścieżka do playit.exe:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Uruchom Playit",
    "settings_playit_site":   "🌐 Strona",

    "dlg_ok":       "OK",
    "dlg_cancel":   "Anuluj",
    "dlg_yes":      "Tak",
    "dlg_no":       "Nie",
    "dlg_warning":  "Uwaga",
    "dlg_error":    "Błąd",
    "dlg_confirm":  "Potwierdzenie",
    "dlg_input":    "Wprowadź dane",
    "dlg_exit":     "Serwer nadal działa. Zatrzymać i wyjść?",
    "dlg_del":      "Usunąć?",
    "dlg_del_article": "Usunąć ten artykuł?",
    "dlg_del_player":  "Usunąć gracza z listy?",

    "browse":       "📁 Wybierz",
    "no_dir":       "Katalog nie ustawiony lub nie istnieje",
}
