LANG_NAME = "Deutsch"
LANG_CODE = "de"

T = {
    "app_name": "CraftControl",
    "app_ready": "Bereit. Wählen Sie einen Server und drücken Sie Start.",

    "tab_console": "⬛ Konsole",
    "tab_servers": "🖥  Server",
    "tab_players": "👥 Spieler",
    "tab_kernels": "⬇ Kernels & Mods",
    "tab_props":   "⚙ Eigenschaften",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Einstellungen",

    "toolbar_open_dir":  "📁 Ordner öffnen",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Server Online",
    "status_offline":    "⚫ Server Offline",

    "console_placeholder": "Befehl eingeben... (z.B. /say Hallo)",
    "console_send":        "▶ Senden",
    "console_clear":       "🗑 Leeren",
    "console_server_offline": "Server läuft nicht",

    "servers_title":     "Meine Server",
    "servers_add":       "+ Hinzufügen",
    "servers_del":       "✕ Löschen",
    "servers_save":      "💾 Speichern",
    "servers_start":     "▶ Starten",
    "servers_stop":      "⏹ Stoppen",
    "servers_settings":  "Server-Einstellungen",
    "servers_name":      "Name:",
    "servers_jar":       "Jar-Datei:",
    "servers_dir":       "Verzeichnis:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Port:",
    "servers_eula":      "EULA akzeptieren",
    "servers_eula_btn":  "eula.txt erstellen",
    "servers_new_name":  "Neuer Servername:",
    "servers_del_confirm": "Diesen Server aus der Liste entfernen?",
    "servers_eula_done": "eula.txt erstellt:",
    "servers_saved":     "Server gespeichert:",
    "servers_no_jar":    "JAR-Datei nicht gefunden. Bitte geben Sie den korrekten Pfad an.",
    "servers_starting":  "Wird gestartet",
    "servers_stopped":   "Server gestoppt",
    "servers_select":    "Server auswählen",
    "servers_no_dir":    "Serververzeichnis zuerst festlegen",
    "servers_rcon_group": "RCON (Live-Spielerliste)",
    "servers_rcon_host": "Host:",
    "servers_rcon_port": "RCON-Port:",
    "servers_rcon_pass": "RCON-Passwort:",
    "servers_rcon_hint": "In server.properties aktivieren: enable-rcon=true, rcon.password=...",
    "servers_api_group": "Benutzerdefinierte Server-API",
    "servers_api_url":   "API-URL:",
    "servers_api_key":   "API-Schlüssel:",
    "servers_api_hint":  "REST-API für Serverdaten. Z.B.: http://localhost:8080",

    "players_nick":      "Spieler-Nickname...",
    "players_add":       "+ Hinzufügen",
    "players_rank":      "Rolle",
    "players_status":    "Status",
    "players_ip":        "IP",
    "players_actions":   "Aktionen",
    "players_kick":      "⚡ Kicken",
    "players_ban":       "🔨 Bannen",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "Online",
    "players_offline":   "Offline",
    "players_refresh":   "🔄 Aktualisieren",
    "players_added":     "Spieler hinzugefügt:",
    "players_server_offline": "Server offline. Befehl:",
    "players_rcon_error": "RCON-Fehler:",
    "players_api_error":  "API-Fehler:",

    "kernels_type":      "Typ:",
    "kernels_fetch":     "🔍 Liste abrufen",
    "kernels_dest":      "Speicherordner...",
    "kernels_browse":    "📁 Durchsuchen",
    "kernels_download":  "⬇ Kernel herunterladen",
    "kernels_fetching":  "Liste wird abgerufen...",
    "kernels_found":     "Gefundene Versionen:",
    "kernels_none":      "Keine Versionen gefunden",
    "kernels_saved":     "Kernel heruntergeladen:",
    "kernels_select":    "Version aus der Liste auswählen",
    "kernels_no_dest":   "Speicherordner festlegen",
    "kernels_downloading": "Herunterladen...",
    "kernels_error":     "Download-Fehler:",
    "kernels_fetch_error": "Abruf-Fehler:",
    "kernels_fetch_start": "Kernels werden abgerufen:",

    "mods_title":        "Mods / Plugins / Datapacks",
    "mods_search_ph":    "Suchen... (Name oder Slug)",
    "mods_search_btn":   "🔍 Suchen",
    "mods_source":       "Quelle:",
    "mods_type":         "Typ:",
    "mods_server_dir":   "Serverordner:",
    "mods_install":      "⬇ Installieren",
    "mods_open_folder":  "📁 Ordner öffnen",
    "mods_installing":   "Installieren...",
    "mods_installed":    "Installiert:",
    "mods_error":        "Fehler:",
    "mods_select":       "Mod aus der Liste auswählen",
    "mods_no_dir":       "Serverordner festlegen",
    "mods_searching":    "Suchen...",
    "mods_no_results":   "Nichts gefunden",
    "mods_results":      "Ergebnisse:",

    "props_load":        "📂 server.properties laden",
    "props_save":        "💾 Speichern",
    "props_saved":       "Gespeichert:",
    "props_loaded":      "Geladen:",

    "wiki_articles":     "Artikel",

    "settings_title":    "Einstellungen",
    "settings_ui_group": "Oberfläche",
    "settings_lang":     "Sprache:",
    "settings_theme":    "Design:",
    "settings_theme_dark":  "Dunkel",
    "settings_theme_light": "Hell",
    "settings_font_size":"Schriftgröße:",
    "settings_accent":   "Akzentfarbe:",
    "settings_accent_green":  "🟢 Grün",
    "settings_accent_blue":   "🔵 Blau",
    "settings_accent_purple": "🟣 Lila",
    "settings_accent_orange": "🟠 Orange",
    "settings_java_group": "Java",
    "settings_java_path": "Java-Pfad:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Automatisch erkennen",
    "settings_save":     "💾 Einstellungen speichern",
    "settings_saved":    "Einstellungen gespeichert!",
    "settings_restart":  "Einige Änderungen werden nach dem Neustart wirksam.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Pfad zu playit.exe:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Playit starten",
    "settings_playit_site":   "🌐 Webseite",

    "dlg_ok":       "OK",
    "dlg_cancel":   "Abbrechen",
    "dlg_yes":      "Ja",
    "dlg_no":       "Nein",
    "dlg_warning":  "Warnung",
    "dlg_error":    "Fehler",
    "dlg_confirm":  "Bestätigen",
    "dlg_input":    "Eingabe",
    "dlg_exit":     "Server läuft noch. Stoppen und beenden?",
    "dlg_del":      "Löschen?",
    "dlg_del_article": "Diesen Artikel löschen?",
    "dlg_del_player":  "Spieler aus Liste entfernen?",

    "browse":       "📁 Durchsuchen",
    "no_dir":       "Verzeichnis nicht gesetzt oder existiert nicht",
}