LANG_NAME = "Español"
LANG_CODE = "es"

T = {
    "app_name": "CraftControl",
    "app_ready": "Listo. Selecciona un servidor y pulsa Iniciar.",

    "tab_console": "⬛ Consola",
    "tab_servers": "🖥 Servidores",
    "tab_players": "👥 Jugadores",
    "tab_kernels": "⬇ Kernels y Mods",
    "tab_props":   "⚙ Propiedades",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Ajustes",

    "toolbar_open_dir":  "📁 Abrir Carpeta",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Servidor en línea",
    "status_offline":    "⚫ Servidor fuera de línea",

    "console_placeholder": "Introduce comando... (ej. /say Hola)",
    "console_send":        "▶ Enviar",
    "console_clear":       "🗑 Limpiar",
    "console_server_offline": "El servidor no está en ejecución",

    "servers_title":     "Mis Servidores",
    "servers_add":       "+ Añadir",
    "servers_del":       "✕ Eliminar",
    "servers_save":      "💾 Guardar",
    "servers_start":     "▶ Iniciar",
    "servers_stop":      "⏹ Detener",
    "servers_settings":  "Ajustes del Servidor",
    "servers_name":      "Nombre:",
    "servers_jar":       "Archivo JAR:",
    "servers_dir":       "Directorio:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Puerto:",
    "servers_eula":      "Aceptar EULA",
    "servers_eula_btn":  "Crear eula.txt",
    "servers_new_name":  "Nombre del nuevo servidor:",
    "servers_del_confirm": "¿Eliminar este servidor de la lista?",
    "servers_eula_done": "eula.txt creado:",
    "servers_saved":     "Servidor guardado:",
    "servers_no_jar":    "Archivo JAR no encontrado. Por favor, establece la ruta correcta.",
    "servers_starting":  "Iniciando",
    "servers_stopped":   "Servidor detenido",
    "servers_select":    "Selecciona un servidor",
    "servers_no_dir":    "Establece primero el directorio del servidor",
    "servers_rcon_group": "RCON (lista de jugadores en vivo)",
    "servers_rcon_host": "Host:",
    "servers_rcon_port": "Puerto RCON:",
    "servers_rcon_pass": "Contraseña RCON:",
    "servers_rcon_hint": "Habilitar en server.properties: enable-rcon=true, rcon.password=...",
    "servers_api_group": "API Personalizada del Servidor",
    "servers_api_url":   "URL de la API:",
    "servers_api_key":   "Clave de la API:",
    "servers_api_hint":  "API REST para datos del servidor. Ej.: http://localhost:8080",

    "players_nick":      "Apodo del jugador...",
    "players_add":       "+ Añadir",
    "players_rank":      "Rol",
    "players_status":    "Estado",
    "players_ip":        "IP",
    "players_actions":   "Acciones",
    "players_kick":      "⚡ Expulsar",
    "players_ban":       "🔨 Banear",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "En línea",
    "players_offline":   "Fuera de línea",
    "players_refresh":   "🔄 Actualizar",
    "players_added":     "Jugador añadido:",
    "players_server_offline": "Servidor fuera de línea. Comando:",
    "players_rcon_error": "Error RCON:",
    "players_api_error":  "Error de API:",

    "kernels_type":      "Tipo:",
    "kernels_fetch":     "🔍 Buscar lista",
    "kernels_dest":      "Carpeta de guardado...",
    "kernels_browse":    "📁 Explorar",
    "kernels_download":  "⬇ Descargar kernel",
    "kernels_fetching":  "Buscando lista...",
    "kernels_found":     "Versiones encontradas:",
    "kernels_none":      "No se encontraron versiones",
    "kernels_saved":     "Kernel descargado:",
    "kernels_select":    "Selecciona una versión de la lista",
    "kernels_no_dest":   "Establece la carpeta de guardado",
    "kernels_downloading": "Descargando...",
    "kernels_error":     "Error de descarga:",
    "kernels_fetch_error": "Error al buscar:",
    "kernels_fetch_start": "Buscando kernels:",

    "mods_title":        "Mods / Plugins / Datapacks",
    "mods_search_ph":    "Buscar... (nombre o slug)",
    "mods_search_btn":   "🔍 Buscar",
    "mods_source":       "Fuente:",
    "mods_type":         "Tipo:",
    "mods_server_dir":   "Carpeta del servidor:",
    "mods_install":      "⬇ Instalar",
    "mods_open_folder":  "📁 Abrir carpeta",
    "mods_installing":   "Instalando...",
    "mods_installed":    "Instalado:",
    "mods_error":        "Error:",
    "mods_select":       "Selecciona un mod de la lista",
    "mods_no_dir":       "Establece la carpeta del servidor",
    "mods_searching":    "Buscando...",
    "mods_no_results":   "Nada encontrado",
    "mods_results":      "Resultados:",

    "props_load":        "📂 Cargar server.properties",
    "props_save":        "💾 Guardar",
    "props_saved":       "Guardado:",
    "props_loaded":      "Cargado:",

    "wiki_articles":     "Artículos",

    "settings_title":    "Ajustes",
    "settings_ui_group": "Interfaz",
    "settings_lang":     "Idioma:",
    "settings_theme":    "Tema:",
    "settings_theme_dark":  "Oscuro",
    "settings_theme_light": "Claro",
    "settings_font_size":"Tamaño de fuente:",
    "settings_accent":   "Color de acento:",
    "settings_accent_green":  "🟢 Verde",
    "settings_accent_blue":   "🔵 Azul",
    "settings_accent_purple": "🟣 Morado",
    "settings_accent_orange": "🟠 Naranja",
    "settings_java_group": "Java",
    "settings_java_path": "Ruta de Java:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Detectar automáticamente",
    "settings_save":     "💾 Guardar Ajustes",
    "settings_saved":    "¡Ajustes guardados!",
    "settings_restart":  "Algunos cambios surtirán efecto después de reiniciar.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Ruta a playit.exe:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Iniciar Playit",
    "settings_playit_site":   "🌐 Sitio web",

    "dlg_ok":       "Aceptar",
    "dlg_cancel":   "Cancelar",
    "dlg_yes":      "Sí",
    "dlg_no":       "No",
    "dlg_warning":  "Advertencia",
    "dlg_error":    "Error",
    "dlg_confirm":  "Confirmar",
    "dlg_input":    "Entrada",
    "dlg_exit":     "El servidor todavía está en ejecución. ¿Detener y salir?",
    "dlg_del":      "¿Eliminar?",
    "dlg_del_article": "¿Eliminar este artículo?",
    "dlg_del_player":  "¿Eliminar al jugador de la lista?",

    "browse":       "📁 Explorar",
    "no_dir":       "Directorio no establecido o no existe",
}