LANG_NAME = "Français"
LANG_CODE = "fr"

T = {
    "app_name": "CraftControl",
    "app_ready": "Prêt. Sélectionnez un serveur et appuyez sur Démarrer.",

    "tab_console": "⬛ Console",
    "tab_servers": "🖥 Serveurs",
    "tab_players": "👥 Joueurs",
    "tab_kernels": "⬇ Noyaux & Mods",
    "tab_props":   "⚙ Propriétés",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Paramètres",

    "toolbar_open_dir":  "📁 Ouvrir le dossier",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Serveur en ligne",
    "status_offline":    "⚫ Serveur hors ligne",

    "console_placeholder": "Entrez une commande... (ex: /say Bonjour)",
    "console_send":        "▶ Envoyer",
    "console_clear":       "🗑 Effacer",
    "console_server_offline": "Le serveur ne fonctionne pas",

    "servers_title":     "Mes Serveurs",
    "servers_add":       "+ Ajouter",
    "servers_del":       "✕ Supprimer",
    "servers_save":      "💾 Sauvegarder",
    "servers_start":     "▶ Démarrer",
    "servers_stop":      "⏹ Arrêter",
    "servers_settings":  "Paramètres du serveur",
    "servers_name":      "Nom :",
    "servers_jar":       "Fichier JAR :",
    "servers_dir":       "Répertoire :",
    "servers_ram":       "RAM :",
    "servers_java":      "Java :",
    "servers_port":      "Port :",
    "servers_eula":      "Accepter l'EULA",
    "servers_eula_btn":  "Créer eula.txt",
    "servers_new_name":  "Nom du nouveau serveur :",
    "servers_del_confirm": "Supprimer ce serveur de la liste ?",
    "servers_eula_done": "eula.txt créé :",
    "servers_saved":     "Serveur sauvegardé :",
    "servers_no_jar":    "Fichier JAR introuvable. Veuillez définir le bon chemin.",
    "servers_starting":  "Démarrage",
    "servers_stopped":   "Serveur arrêté",
    "servers_select":    "Sélectionnez un serveur",
    "servers_no_dir":    "Définissez d'abord le répertoire du serveur",
    "servers_rcon_group": "RCON (liste des joueurs en direct)",
    "servers_rcon_host": "Hôte :",
    "servers_rcon_port": "Port RCON :",
    "servers_rcon_pass": "Mot de passe RCON :",
    "servers_rcon_hint": "Activer dans server.properties : enable-rcon=true, rcon.password=...",
    "servers_api_group": "API personnalisée du serveur",
    "servers_api_url":   "URL de l'API :",
    "servers_api_key":   "Clé API :",
    "servers_api_hint":  "API REST pour les données du serveur. Ex : http://localhost:8080",

    "players_nick":      "Pseudo du joueur...",
    "players_add":       "+ Ajouter",
    "players_rank":      "Rôle",
    "players_status":    "Statut",
    "players_ip":        "IP",
    "players_actions":   "Actions",
    "players_kick":      "⚡ Expulser",
    "players_ban":       "🔨 Bannir",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "En ligne",
    "players_offline":   "Hors ligne",
    "players_refresh":   "🔄 Rafraîchir",
    "players_added":     "Joueur ajouté :",
    "players_server_offline": "Serveur hors ligne. Commande :",
    "players_rcon_error": "Erreur RCON :",
    "players_api_error":  "Erreur API :",

    "kernels_type":      "Type :",
    "kernels_fetch":     "🔍 Rechercher la liste",
    "kernels_dest":      "Dossier de sauvegarde...",
    "kernels_browse":    "📁 Parcourir",
    "kernels_download":  "⬇ Télécharger le noyau",
    "kernels_fetching":  "Recherche de la liste...",
    "kernels_found":     "Versions trouvées :",
    "kernels_none":      "Aucune version trouvée",
    "kernels_saved":     "Noyau téléchargé :",
    "kernels_select":    "Sélectionnez une version dans la liste",
    "kernels_no_dest":   "Définir le dossier de sauvegarde",
    "kernels_downloading": "Téléchargement en cours...",
    "kernels_error":     "Erreur de téléchargement :",
    "kernels_fetch_error": "Erreur de recherche :",
    "kernels_fetch_start": "Recherche des noyaux :",

    "mods_title":        "Mods / Plugins / Datapacks",
    "mods_search_ph":    "Rechercher... (nom ou slug)",
    "mods_search_btn":   "🔍 Rechercher",
    "mods_source":       "Source :",
    "mods_type":         "Type :",
    "mods_server_dir":   "Dossier du serveur :",
    "mods_install":      "⬇ Installer",
    "mods_open_folder":  "📁 Ouvrir le dossier",
    "mods_installing":   "Installation en cours...",
    "mods_installed":    "Installé :",
    "mods_error":        "Erreur :",
    "mods_select":       "Sélectionnez un mod dans la liste",
    "mods_no_dir":       "Définir le dossier du serveur",
    "mods_searching":    "Recherche en cours...",
    "mods_no_results":   "Aucun résultat",
    "mods_results":      "Résultats :",

    "props_load":        "📂 Charger server.properties",
    "props_save":        "💾 Sauvegarder",
    "props_saved":       "Sauvegardé :",
    "props_loaded":      "Chargé :",

    "wiki_articles":     "Articles",

    "settings_title":    "Paramètres",
    "settings_ui_group": "Interface",
    "settings_lang":     "Langue :",
    "settings_theme":    "Thème :",
    "settings_theme_dark":  "Sombre",
    "settings_theme_light": "Clair",
    "settings_font_size":"Taille de police :",
    "settings_accent":   "Couleur d'accentuation :",
    "settings_accent_green":  "🟢 Vert",
    "settings_accent_blue":   "🔵 Bleu",
    "settings_accent_purple": "🟣 Violet",
    "settings_accent_orange": "🟠 Orange",
    "settings_java_group": "Java",
    "settings_java_path": "Chemin Java :",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Détection automatique",
    "settings_save":     "💾 Enregistrer les paramètres",
    "settings_saved":    "Paramètres enregistrés !",
    "settings_restart":  "Certains changements prendront effet après le redémarrage.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Chemin vers playit.exe :",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Lancer Playit",
    "settings_playit_site":   "🌐 Site web",

    "dlg_ok":       "OK",
    "dlg_cancel":   "Annuler",
    "dlg_yes":      "Oui",
    "dlg_no":       "Non",
    "dlg_warning":  "Attention",
    "dlg_error":    "Erreur",
    "dlg_confirm":  "Confirmer",
    "dlg_input":    "Entrée",
    "dlg_exit":     "Le serveur est toujours en cours d'exécution. Arrêter et quitter ?",
    "dlg_del":      "Supprimer ?",
    "dlg_del_article": "Supprimer cet article ?",
    "dlg_del_player":  "Retirer le joueur de la liste ?",

    "browse":       "📁 Parcourir",
    "no_dir":       "Répertoire non défini ou inexistant",
}