LANG_NAME = "Italiano"
LANG_CODE = "it"

T = {
    "app_name": "CraftControl",
    "app_ready": "Pronto. Seleziona un server e premi Avvia.",

    "tab_console": "⬛ Console",
    "tab_servers": "🖥 Server",
    "tab_players": "👥 Giocatori",
    "tab_kernels": "⬇ Kernel & Mod",
    "tab_props":   "⚙ Proprietà",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Impostazioni",

    "toolbar_open_dir":  "📁 Apri Cartella",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Server Online",
    "status_offline":    "⚫ Server Offline",

    "console_placeholder": "Inserisci comando... (es. /say Ciao)",
    "console_send":        "▶ Invia",
    "console_clear":       "🗑 Pulisci",
    "console_server_offline": "Il server non è in esecuzione",

    "servers_title":     "I Miei Server",
    "servers_add":       "+ Aggiungi",
    "servers_del":       "✕ Elimina",
    "servers_save":      "💾 Salva",
    "servers_start":     "▶ Avvia",
    "servers_stop":      "⏹ Ferma",
    "servers_settings":  "Impostazioni Server",
    "servers_name":      "Nome:",
    "servers_jar":       "File JAR:",
    "servers_dir":       "Directory:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Porta:",
    "servers_eula":      "Accetta EULA",
    "servers_eula_btn":  "Crea eula.txt",
    "servers_new_name":  "Nome nuovo server:",
    "servers_del_confirm": "Rimuovere questo server dalla lista?",
    "servers_eula_done": "eula.txt creato:",
    "servers_saved":     "Server salvato:",
    "servers_no_jar":    "File JAR non trovato. Imposta il percorso corretto.",
    "servers_starting":  "Avvio in corso",
    "servers_stopped":   "Server fermato",
    "servers_select":    "Seleziona un server",
    "servers_no_dir":    "Imposta prima la directory del server",
    "servers_rcon_group": "RCON (lista giocatori live)",
    "servers_rcon_host": "Host:",
    "servers_rcon_port": "Porta RCON:",
    "servers_rcon_pass": "Password RCON:",
    "servers_rcon_hint": "Abilita in server.properties: enable-rcon=true, rcon.password=...",
    "servers_api_group": "API Server Personalizzata",
    "servers_api_url":   "URL API:",
    "servers_api_key":   "Chiave API:",
    "servers_api_hint":  "API REST per dati del server. Es: http://localhost:8080",

    "players_nick":      "Nickname giocatore...",
    "players_add":       "+ Aggiungi",
    "players_rank":      "Ruolo",
    "players_status":    "Stato",
    "players_ip":        "IP",
    "players_actions":   "Azioni",
    "players_kick":      "⚡ Espelli",
    "players_ban":       "🔨 Banna",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "Online",
    "players_offline":   "Offline",
    "players_refresh":   "🔄 Aggiorna",
    "players_added":     "Giocatore aggiunto:",
    "players_server_offline": "Server offline. Comando:",
    "players_rcon_error": "Errore RCON:",
    "players_api_error":  "Errore API:",

    "kernels_type":      "Tipo:",
    "kernels_fetch":     "🔍 Cerca lista",
    "kernels_dest":      "Cartella di salvataggio...",
    "kernels_browse":    "📁 Sfoglia",
    "kernels_download":  "⬇ Scarica kernel",
    "kernels_fetching":  "Ricerca lista...",
    "kernels_found":     "Versioni trovate:",
    "kernels_none":      "Nessuna versione trovata",
    "kernels_saved":     "Kernel scaricato:",
    "kernels_select":    "Seleziona una versione dalla lista",
    "kernels_no_dest":   "Imposta cartella di salvataggio",
    "kernels_downloading": "Download in corso...",
    "kernels_error":     "Errore download:",
    "kernels_fetch_error": "Errore ricerca:",
    "kernels_fetch_start": "Ricerca kernel:",

    "mods_title":        "Mod / Plugin / Datapack",
    "mods_search_ph":    "Cerca... (nome o slug)",
    "mods_search_btn":   "🔍 Cerca",
    "mods_source":       "Sorgente:",
    "mods_type":         "Tipo:",
    "mods_server_dir":   "Cartella server:",
    "mods_install":      "⬇ Installa",
    "mods_open_folder":  "📁 Apri cartella",
    "mods_installing":   "Installazione in corso...",
    "mods_installed":    "Installato:",
    "mods_error":        "Errore:",
    "mods_select":       "Seleziona una mod dalla lista",
    "mods_no_dir":       "Imposta cartella server",
    "mods_searching":    "Ricerca in corso...",
    "mods_no_results":   "Nessun risultato trovato",
    "mods_results":      "Risultati:",

    "props_load":        "📂 Carica server.properties",
    "props_save":        "💾 Salva",
    "props_saved":       "Salvato:",
    "props_loaded":      "Caricato:",

    "wiki_articles":     "Articoli",

    "settings_title":    "Impostazioni",
    "settings_ui_group": "Interfaccia",
    "settings_lang":     "Lingua:",
    "settings_theme":    "Tema:",
    "settings_theme_dark":  "Scuro",
    "settings_theme_light": "Chiaro",
    "settings_font_size":"Dimensione font:",
    "settings_accent":   "Colore accento:",
    "settings_accent_green":  "🟢 Verde",
    "settings_accent_blue":   "🔵 Blu",
    "settings_accent_purple": "🟣 Viola",
    "settings_accent_orange": "🟠 Arancione",
    "settings_java_group": "Java",
    "settings_java_path": "Percorso Java:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Auto-detect",
    "settings_save":     "💾 Salva Impostazioni",
    "settings_saved":    "Impostazioni salvate!",
    "settings_restart":  "Alcune modifiche avranno effetto dopo il riavvio.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Percorso di playit.exe:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Avvia Playit",
    "settings_playit_site":   "🌐 Sito Web",

    "dlg_ok":       "OK",
    "dlg_cancel":   "Annulla",
    "dlg_yes":      "Sì",
    "dlg_no":       "No",
    "dlg_warning":  "Attenzione",
    "dlg_error":    "Errore",
    "dlg_confirm":  "Conferma",
    "dlg_input":    "Input",
    "dlg_exit":     "Il server è ancora in esecuzione. Fermare e uscire?",
    "dlg_del":      "Eliminare?",
    "dlg_del_article": "Eliminare questo articolo?",
    "dlg_del_player":  "Rimuovere il giocatore dalla lista?",

    "browse":       "📁 Sfoglia",
    "no_dir":       "Directory non impostata o non esiste",
}