LANG_NAME = "日本"
LANG_CODE = "ja"

T = {
    "app_name": "CraftControl",
    "app_ready": "準備完了。サーバーを選択して「開始」を押してください。",

    "tab_console": "⬛ コンソール",
    "tab_servers": "🖥  サーバー",
    "tab_players": "👥 プレイヤー",
    "tab_kernels": "⬇ カーネル & Mod",
    "tab_props":   "⚙ プロパティ",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ 設定",

    "toolbar_open_dir":  "📁 フォルダを開く",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 サーバー稼働中",
    "status_offline":    "⚫ サーバー停止中",

    "console_placeholder": "コマンドを入力... (例: /say Hello)",
    "console_send":        "▶ 送信",
    "console_clear":       "🗑 クリア",
    "console_server_offline": "サーバーは実行されていません",

    "servers_title":     "マイサーバー",
    "servers_add":       "+ 追加",
    "servers_del":       "✕ 削除",
    "servers_save":      "💾 保存",
    "servers_start":     "▶ 開始",
    "servers_stop":      "⏹ 停止",
    "servers_settings":  "サーバー設定",
    "servers_name":      "名前:",
    "servers_jar":       "Jarファイル:",
    "servers_dir":       "ディレクトリ:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "ポート:",
    "servers_eula":      "EULAに同意",
    "servers_eula_btn":  "eula.txtを作成",
    "servers_new_name":  "新しいサーバー名:",
    "servers_del_confirm": "このサーバーをリストから削除しますか？",
    "servers_eula_done": "eula.txtを作成しました:",
    "servers_saved":     "サーバーを保存しました:",
    "servers_no_jar":    "JARファイルが見つかりません。正しいパスを設定してください。",
    "servers_starting":  "起動中",
    "servers_stopped":   "サーバー停止",
    "servers_select":    "サーバーを選択",
    "servers_no_dir":    "まずサーバーディレクトリを設定してください",
    "servers_rcon_group": "RCON (ライブプレイヤーリスト)",
    "servers_rcon_host": "ホスト:",
    "servers_rcon_port": "RCONポート:",
    "servers_rcon_pass": "RCONパスワード:",
    "servers_rcon_hint": "server.propertiesで有効化: enable-rcon=true, rcon.password=...",
    "servers_api_group": "カスタムサーバーAPI",
    "servers_api_url":   "API URL:",
    "servers_api_key":   "APIキー:",
    "servers_api_hint":  "サーバーデータ用REST API。例: http://localhost:8080",

    "players_nick":      "プレイヤーのニックネーム...",
    "players_add":       "+ 追加",
    "players_rank":      "役割",
    "players_status":    "ステータス",
    "players_ip":        "IP",
    "players_actions":   "アクション",
    "players_kick":      "⚡ キック",
    "players_ban":       "🔨 バン",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "オンライン",
    "players_offline":   "オフライン",
    "players_refresh":   "🔄 更新",
    "players_added":     "プレイヤーを追加しました:",
    "players_server_offline": "サーバーオフライン。コマンド:",
    "players_rcon_error": "RCONエラー:",
    "players_api_error":  "APIエラー:",

    "kernels_type":      "タイプ:",
    "kernels_fetch":     "🔍 リスト取得",
    "kernels_dest":      "保存フォルダ...",
    "kernels_browse":    "📁 ブラウズ",
    "kernels_download":  "⬇ カーネルをダウンロード",
    "kernels_fetching":  "リスト取得中...",
    "kernels_found":     "バージョンが見つかりました:",
    "kernels_none":      "バージョンが見つかりません",
    "kernels_saved":     "カーネルをダウンロードしました:",
    "kernels_select":    "リストからバージョンを選択",
    "kernels_no_dest":   "保存フォルダを設定してください",
    "kernels_downloading": "ダウンロード中...",
    "kernels_error":     "ダウンロードエラー:",
    "kernels_fetch_error": "取得エラー:",
    "kernels_fetch_start": "カーネルを取得中:",

    "mods_title":        "Mod / プラグイン / データパック",
    "mods_search_ph":    "検索... (名前またはスラッグ)",
    "mods_search_btn":   "🔍 検索",
    "mods_source":       "ソース:",
    "mods_type":         "タイプ:",
    "mods_server_dir":   "サーバーフォルダ:",
    "mods_install":      "⬇ インストール",
    "mods_open_folder":  "📁 フォルダを開く",
    "mods_installing":   "インストール中...",
    "mods_installed":    "インストール済み:",
    "mods_error":        "エラー:",
    "mods_select":       "リストからModを選択",
    "mods_no_dir":       "サーバーフォルダを設定してください",
    "mods_searching":    "検索中...",
    "mods_no_results":   "何も見つかりませんでした",
    "mods_results":      "結果:",

    "props_load":        "📂 server.propertiesを読み込む",
    "props_save":        "💾 保存",
    "props_saved":       "保存しました:",
    "props_loaded":      "読み込みました:",

    "wiki_articles":     "記事",

    "settings_title":    "設定",
    "settings_ui_group": "インターフェース",
    "settings_lang":     "言語:",
    "settings_theme":    "テーマ:",
    "settings_theme_dark":  "ダーク",
    "settings_theme_light": "ライト",
    "settings_font_size":"フォントサイズ:",
    "settings_accent":   "アクセントカラー:",
    "settings_accent_green":  "🟢 グリーン",
    "settings_accent_blue":   "🔵 ブルー",
    "settings_accent_purple": "🟣 パープル",
    "settings_accent_orange": "🟠 オレンジ",
    "settings_java_group": "Java",
    "settings_java_path": "Javaパス:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 自動検出",
    "settings_save":     "💾 設定を保存",
    "settings_saved":    "設定を保存しました！",
    "settings_restart":  "一部の変更は再起動後に有効になります。",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "playit.exeへのパス:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Playitを起動",
    "settings_playit_site":   "🌐 ウェブサイト",

    "dlg_ok":       "OK",
    "dlg_cancel":   "キャンセル",
    "dlg_yes":      "はい",
    "dlg_no":       "いいえ",
    "dlg_warning":  "警告",
    "dlg_error":    "エラー",
    "dlg_confirm":  "確認",
    "dlg_input":    "入力",
    "dlg_exit":     "サーバーはまだ実行中です。停止して終了しますか？",
    "dlg_del":      "削除しますか？",
    "dlg_del_article": "この記事を削除しますか？",
    "dlg_del_player":  "プレイヤーをリストから削除しますか？",

    "browse":       "📁 ブラウズ",
    "no_dir":       "ディレクトリが設定されていないか、存在しません",
}