LANG_NAME = "Nederlands"
LANG_CODE = "nl"

T = {
    "app_name": "CraftControl",
    "app_ready": "Klaar. Selecteer een server en druk op Start.",

    "tab_console": "⬛ Console",
    "tab_servers": "🖥 Servers",
    "tab_players": "👥 Spelers",
    "tab_kernels": "⬇ Kernels & Mods",
    "tab_props":   "⚙ Eigenschappen",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Instellingen",

    "toolbar_open_dir":  "📁 Map Openen",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Server Online",
    "status_offline":    "⚫ Server Offline",

    "console_placeholder": "Voer commando in... (bijv. /say Hallo)",
    "console_send":        "▶ Verzenden",
    "console_clear":       "🗑 Leegmaken",
    "console_server_offline": "Server draait niet",

    "servers_title":     "Mijn Servers",
    "servers_add":       "+ Toevoegen",
    "servers_del":       "✕ Verwijderen",
    "servers_save":      "💾 Opslaan",
    "servers_start":     "▶ Starten",
    "servers_stop":      "⏹ Stoppen",
    "servers_settings":  "Serverinstellingen",
    "servers_name":      "Naam:",
    "servers_jar":       "Jar-bestand:",
    "servers_dir":       "Directory:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Poort:",
    "servers_eula":      "EULA Accepteren",
    "servers_eula_btn":  "Maak eula.txt aan",
    "servers_new_name":  "Nieuwe servernaam:",
    "servers_del_confirm": "Deze server uit de lijst verwijderen?",
    "servers_eula_done": "eula.txt aangemaakt:",
    "servers_saved":     "Server opgeslagen:",
    "servers_no_jar":    "JAR-bestand niet gevonden. Stel het juiste pad in.",
    "servers_starting":  "Starten",
    "servers_stopped":   "Server gestopt",
    "servers_select":    "Selecteer een server",
    "servers_no_dir":    "Stel eerst de serverdirectory in",
    "servers_rcon_group": "RCON (live spelerslijst)",
    "servers_rcon_host": "Host:",
    "servers_rcon_port": "RCON-poort:",
    "servers_rcon_pass": "RCON-wachtwoord:",
    "servers_rcon_hint": "Inschakelen in server.properties: enable-rcon=true, rcon.password=...",
    "servers_api_group": "Aangepaste Server API",
    "servers_api_url":   "API URL:",
    "servers_api_key":   "API-sleutel:",
    "servers_api_hint":  "REST API voor servergegevens. Bijv.: http://localhost:8080",

    "players_nick":      "Spelersnaam...",
    "players_add":       "+ Toevoegen",
    "players_rank":      "Rol",
    "players_status":    "Status",
    "players_ip":        "IP",
    "players_actions":   "Acties",
    "players_kick":      "⚡ Kicken",
    "players_ban":       "🔨 Bannen",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "Online",
    "players_offline":   "Offline",
    "players_refresh":   "🔄 Vernieuwen",
    "players_added":     "Speler toegevoegd:",
    "players_server_offline": "Server offline. Commando:",
    "players_rcon_error": "RCON-fout:",
    "players_api_error":  "API-fout:",

    "kernels_type":      "Type:",
    "kernels_fetch":     "🔍 Lijst ophalen",
    "kernels_dest":      "Opslagmap...",
    "kernels_browse":    "📁 Bladeren",
    "kernels_download":  "⬇ Kernel downloaden",
    "kernels_fetching":  "Lijst wordt opgehaald...",
    "kernels_found":     "Versies gevonden:",
    "kernels_none":      "Geen versies gevonden",
    "kernels_saved":     "Kernel gedownload:",
    "kernels_select":    "Selecteer een versie uit de lijst",
    "kernels_no_dest":   "Stel opslagmap in",
    "kernels_downloading": "Downloaden...",
    "kernels_error":     "Downloadfout:",
    "kernels_fetch_error": "Ophaalfout:",
    "kernels_fetch_start": "Kernels worden opgehaald:",

    "mods_title":        "Mods / Plugins / Datapacks",
    "mods_search_ph":    "Zoeken... (naam of slug)",
    "mods_search_btn":   "🔍 Zoeken",
    "mods_source":       "Bron:",
    "mods_type":         "Type:",
    "mods_server_dir":   "Servermap:",
    "mods_install":      "⬇ Installeren",
    "mods_open_folder":  "📁 Map openen",
    "mods_installing":   "Installeren...",
    "mods_installed":    "Geïnstalleerd:",
    "mods_error":        "Fout:",
    "mods_select":       "Selecteer een mod uit de lijst",
    "mods_no_dir":       "Stel servermap in",
    "mods_searching":    "Zoeken...",
    "mods_no_results":   "Niets gevonden",
    "mods_results":      "Resultaten:",

    "props_load":        "📂 server.properties laden",
    "props_save":        "💾 Opslaan",
    "props_saved":       "Opgeslagen:",
    "props_loaded":      "Geladen:",

    "wiki_articles":     "Artikelen",

    "settings_title":    "Instellingen",
    "settings_ui_group": "Interface",
    "settings_lang":     "Taal:",
    "settings_theme":    "Thema:",
    "settings_theme_dark":  "Donker",
    "settings_theme_light": "Licht",
    "settings_font_size":"Lettergrootte:",
    "settings_accent":   "Accentkleur:",
    "settings_accent_green":  "🟢 Groen",
    "settings_accent_blue":   "🔵 Blauw",
    "settings_accent_purple": "🟣 Paars",
    "settings_accent_orange": "🟠 Oranje",
    "settings_java_group": "Java",
    "settings_java_path": "Java-pad:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Automatisch detecteren",
    "settings_save":     "💾 Instellingen opslaan",
    "settings_saved":    "Instellingen opgeslagen!",
    "settings_restart":  "Sommige wijzigingen worden van kracht na herstart.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Pad naar playit.exe:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Playit starten",
    "settings_playit_site":   "🌐 Website",

    "dlg_ok":       "OK",
    "dlg_cancel":   "Annuleren",
    "dlg_yes":      "Ja",
    "dlg_no":       "Nee",
    "dlg_warning":  "Waarschuwing",
    "dlg_error":    "Fout",
    "dlg_confirm":  "Bevestigen",
    "dlg_input":    "Invoer",
    "dlg_exit":     "Server draait nog. Stoppen en afsluiten?",
    "dlg_del":      "Verwijderen?",
    "dlg_del_article": "Dit artikel verwijderen?",
    "dlg_del_player":  "Speler uit lijst verwijderen?",

    "browse":       "📁 Bladeren",
    "no_dir":       "Directory niet ingesteld of bestaat niet",
}