LANG_NAME = "România"
LANG_CODE = "ro"

T = {
    "app_name": "CraftControl",
    "app_ready": "Pregătit. Selectați un server și apăsați Start.",

    "tab_console": "⬛ Consolă",
    "tab_servers": "🖥 Servere",
    "tab_players": "👥 Jucători",
    "tab_kernels": "⬇ Nuclee & Moduri",
    "tab_props":   "⚙ Proprietăți",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ Setări",

    "toolbar_open_dir":  "📁 Deschide Folderul",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Server Online",
    "status_offline":    "⚫ Server Offline",

    "console_placeholder": "Introduceți comandă... (ex: /say Salut)",
    "console_send":        "▶ Trimite",
    "console_clear":       "🗑 Curăță",
    "console_server_offline": "Serverul nu rulează",

    "servers_title":     "Serverele Mele",
    "servers_add":       "+ Adaugă",
    "servers_del":       "✕ Șterge",
    "servers_save":      "💾 Salvează",
    "servers_start":     "▶ Pornire",
    "servers_stop":      "⏹ Oprire",
    "servers_settings":  "Setări Server",
    "servers_name":      "Nume:",
    "servers_jar":       "Fișier Jar:",
    "servers_dir":       "Director:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Port:",
    "servers_eula":      "Acceptă EULA",
    "servers_eula_btn":  "Creează eula.txt",
    "servers_new_name":  "Nume server nou:",
    "servers_del_confirm": "Eliminați acest server din listă?",
    "servers_eula_done": "eula.txt creat:",
    "servers_saved":     "Server salvat:",
    "servers_no_jar":    "Fișierul JAR nu a fost găsit. Vă rugăm să setați calea corectă.",
    "servers_starting":  "Pornire",
    "servers_stopped":   "Server oprit",
    "servers_select":    "Selectați un server",
    "servers_no_dir":    "Setați mai întâi directorul serverului",
    "servers_rcon_group": "RCON (listă jucători live)",
    "servers_rcon_host": "Host:",
    "servers_rcon_port": "Port RCON:",
    "servers_rcon_pass": "Parolă RCON:",
    "servers_rcon_hint": "Activați în server.properties: enable-rcon=true, rcon.password=...",
    "servers_api_group": "API Personalizat Server",
    "servers_api_url":   "URL API:",
    "servers_api_key":   "Cheie API:",
    "servers_api_hint":  "API REST pentru datele serverului. Ex: http://localhost:8080",

    "players_nick":      "Nume jucător...",
    "players_add":       "+ Adaugă",
    "players_rank":      "Rol",
    "players_status":    "Status",
    "players_ip":        "IP",
    "players_actions":   "Acțiuni",
    "players_kick":      "⚡ Elimină",
    "players_ban":       "🔨 Interzice",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 TP",
    "players_online":    "Online",
    "players_offline":   "Offline",
    "players_refresh":   "🔄 Reîmprospătează",
    "players_added":     "Jucător adăugat:",
    "players_server_offline": "Server offline. Comandă:",
    "players_rcon_error": "Eroare RCON:",
    "players_api_error":  "Eroare API:",

    "kernels_type":      "Tip:",
    "kernels_fetch":     "🔍 Caută lista",
    "kernels_dest":      "Director salvare...",
    "kernels_browse":    "📁 Răsfoiește",
    "kernels_download":  "⬇ Descarcă nucleu",
    "kernels_fetching":  "Se caută lista...",
    "kernels_found":     "Versiuni găsite:",
    "kernels_none":      "Nicio versiune găsită",
    "kernels_saved":     "Nucleu descărcat:",
    "kernels_select":    "Selectați o versiune din listă",
    "kernels_no_dest":   "Setați directorul de salvare",
    "kernels_downloading": "Se descarcă...",
    "kernels_error":     "Eroare descărcare:",
    "kernels_fetch_error": "Eroare căutare:",
    "kernels_fetch_start": "Se caută nuclee:",

    "mods_title":        "Moduri / Pluginuri / Datapack-uri",
    "mods_search_ph":    "Caută... (nume sau slug)",
    "mods_search_btn":   "🔍 Caută",
    "mods_source":       "Sursă:",
    "mods_type":         "Tip:",
    "mods_server_dir":   "Director server:",
    "mods_install":      "⬇ Instalează",
    "mods_open_folder":  "📁 Deschide folderul",
    "mods_installing":   "Se instalează...",
    "mods_installed":    "Instalat:",
    "mods_error":        "Eroare:",
    "mods_select":       "Selectați un mod din listă",
    "mods_no_dir":       "Setați directorul serverului",
    "mods_searching":    "Se caută...",
    "mods_no_results":   "Nimic găsit",
    "mods_results":      "Rezultate:",

    "props_load":        "📂 Încarcă server.properties",
    "props_save":        "💾 Salvează",
    "props_saved":       "Salvat:",
    "props_loaded":      "Încărcat:",

    "wiki_articles":     "Articole",

    "settings_title":    "Setări",
    "settings_ui_group": "Interfață",
    "settings_lang":     "Limbă:",
    "settings_theme":    "Temă:",
    "settings_theme_dark":  "Întunecată",
    "settings_theme_light": "Deschisă",
    "settings_font_size":"Dimensiune font:",
    "settings_accent":   "Culoare accent:",
    "settings_accent_green":  "🟢 Verde",
    "settings_accent_blue":   "🔵 Albastru",
    "settings_accent_purple": "🟣 Violet",
    "settings_accent_orange": "🟠 Portocaliu",
    "settings_java_group": "Java",
    "settings_java_path": "Cale Java:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Detectare automată",
    "settings_save":     "💾 Salvează Setări",
    "settings_saved":    "Setări salvate!",
    "settings_restart":  "Unele modificări vor intra în vigoare după repornire.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "Cale către playit.exe:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Lansează Playit",
    "settings_playit_site":   "🌐 Website",

    "dlg_ok":       "OK",
    "dlg_cancel":   "Anulare",
    "dlg_yes":      "Da",
    "dlg_no":       "Nu",
    "dlg_warning":  "Atenție",
    "dlg_error":    "Eroare",
    "dlg_confirm":  "Confirmă",
    "dlg_input":    "Introducere",
    "dlg_exit":     "Serverul rulează încă. Opriți și ieșiți?",
    "dlg_del":      "Șterge?",
    "dlg_del_article": "Ștergeți acest articol?",
    "dlg_del_player":  "Eliminați jucătorul din listă?",

    "browse":       "📁 Răsfoiește",
    "no_dir":       "Directorul nu este setat sau nu există",
}