LANG_NAME = "Türkçe"
LANG_CODE = "tr"

T = {
    "app_name": "CraftControl",
    "app_ready": "Hazır. Bir sunucu seçin ve Başlat'a basın.",

    "tab_console": "⬛ Konsol",
    "tab_servers": "🖥 Sunucular",
    "tab_players": "👥 Oyuncular",
    "tab_kernels": "⬇ Çekirdekler ve Modlar",
    "tab_props":   "⚙ Ayarlar",
    "tab_wiki":    "📖 Vikipedya",
    "tab_settings":"⚙ Ayarlar",

    "toolbar_open_dir":  "📁 Klasörü Aç",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 Sunucu Çevrimiçi",
    "status_offline":    "⚫ Sunucu Çevrimdışı",

    "console_placeholder": "Komut girin... (örn. /say Merhaba)",
    "console_send":        "▶ Gönder",
    "console_clear":       "🗑 Temizle",
    "console_server_offline": "Sunucu çalışmıyor",

    "servers_title":     "Sunucularım",
    "servers_add":       "+ Ekle",
    "servers_del":       "✕ Sil",
    "servers_save":      "💾 Kaydet",
    "servers_start":     "▶ Başlat",
    "servers_stop":      "⏹ Durdur",
    "servers_settings":  "Sunucu Ayarları",
    "servers_name":      "Ad:",
    "servers_jar":       "Jar dosyası:",
    "servers_dir":       "Dizin:",
    "servers_ram":       "RAM:",
    "servers_java":      "Java:",
    "servers_port":      "Port:",
    "servers_eula":      "EULA Kabul Et",
    "servers_eula_btn":  "eula.txt Oluştur",
    "servers_new_name":  "Yeni sunucu adı:",
    "servers_del_confirm": "Bu sunucuyu listeden kaldır?",
    "servers_eula_done": "eula.txt oluşturuldu:",
    "servers_saved":     "Sunucu kaydedildi:",
    "servers_no_jar":    "JAR dosyası bulunamadı. Lütfen doğru yolu belirtin.",
    "servers_starting":  "Başlatılıyor",
    "servers_stopped":   "Sunucu durduruldu",
    "servers_select":    "Bir sunucu seçin",
    "servers_no_dir":    "Önce sunucu dizinini ayarlayın",
    "servers_rcon_group": "RCON (canlı oyuncu listesi)",
    "servers_rcon_host": "Sunucu:",
    "servers_rcon_port": "RCON portu:",
    "servers_rcon_pass": "RCON şifresi:",
    "servers_rcon_hint": "Sunucu özelliklerinde etkinleştirin: enable-rcon=true, rcon.password=...",
    "servers_api_group": "Özel Sunucu API'si",
    "servers_api_url":   "API URL'si:",
    "servers_api_key":   "API anahtarı:",
    "servers_api_hint":  "Sunucu verileri için REST API. Örn: http://localhost:8080",

    "players_nick":      "Oyuncu takma adı...",
    "players_add":       "+ Ekle",
    "players_rank":      "Rol",
    "players_status":    "Durum",
    "players_ip":        "IP",
    "players_actions":   "Eylemler",
    "players_kick":      "⚡ At",
    "players_ban":       "🔨 Yasakla",
    "players_op":        "⭐ OP Yap",
    "players_tp":        "🌐 Işınla",
    "players_online":    "Çevrimiçi",
    "players_offline":   "Çevrimdışı",
    "players_refresh":   "🔄 Yenile",
    "players_added":     "Oyuncu eklendi:",
    "players_server_offline": "Sunucu çevrimdışı. Komut:",
    "players_rcon_error": "RCON hatası:",
    "players_api_error":  "API hatası:",

    "kernels_type":      "Tür:",
    "kernels_fetch":     "🔍 Listeyi Getir",
    "kernels_dest":      "Kaydetme klasörü...",
    "kernels_browse":    "📁 Gözat",
    "kernels_download":  "⬇ Çekirdek İndir",
    "kernels_fetching":  "Liste getiriliyor...",
    "kernels_found":     "Sürümler bulundu:",
    "kernels_none":      "Sürüm bulunamadı",
    "kernels_saved":     "Çekirdek indirildi:",
    "kernels_select":    "Listeden bir sürüm seçin",
    "kernels_no_dest":   "Kaydetme klasörünü ayarla",
    "kernels_downloading": "İndiriliyor...",
    "kernels_error":     "İndirme hatası:",
    "kernels_fetch_error": "Getirme hatası:",
    "kernels_fetch_start": "Çekirdekler getiriliyor:",

    "mods_title":        "Modlar / Eklentiler / Veri Paketleri",
    "mods_search_ph":    "Ara... (ad veya slug)",
    "mods_search_btn":   "🔍 Ara",
    "mods_source":       "Kaynak:",
    "mods_type":         "Tür:",
    "mods_server_dir":   "Sunucu klasörü:",
    "mods_install":      "⬇ Yükle",
    "mods_open_folder":  "📁 Klasörü aç",
    "mods_installing":   "Yükleniyor...",
    "mods_installed":    "Yüklendi:",
    "mods_error":        "Hata:",
    "mods_select":       "Listeden bir mod seçin",
    "mods_no_dir":       "Sunucu klasörünü ayarla",
    "mods_searching":    "Aranıyor...",
    "mods_no_results":   "Hiçbir şey bulunamadı",
    "mods_results":      "Sonuçlar:",

    "props_load":        "📂 server.properties yükle",
    "props_save":        "💾 Kaydet",
    "props_saved":       "Kaydedildi:",
    "props_loaded":      "Yüklendi:",

    "wiki_articles":     "Makaleler",

    "settings_title":    "Ayarlar",
    "settings_ui_group": "Arayüz",
    "settings_lang":     "Dil:",
    "settings_theme":    "Tema:",
    "settings_theme_dark":  "Koyu",
    "settings_theme_light": "Açık",
    "settings_font_size":"Yazı tipi boyutu:",
    "settings_accent":   "Vurgu rengi:",
    "settings_accent_green":  "🟢 Yeşil",
    "settings_accent_blue":   "🔵 Mavi",
    "settings_accent_purple": "🟣 Mor",
    "settings_accent_orange": "🟠 Turuncu",
    "settings_java_group": "Java",
    "settings_java_path": "Java yolu:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 Otomatik algıla",
    "settings_save":     "💾 Ayarları Kaydet",
    "settings_saved":    "Ayarlar kaydedildi!",
    "settings_restart":  "Bazı değişiklikler yeniden başlatıldıktan sonra geçerli olacaktır.",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "playit.exe yolu:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ Playit Başlat",
    "settings_playit_site":   "🌐 Web Sitesi",

    "dlg_ok":       "Tamam",
    "dlg_cancel":   "İptal",
    "dlg_yes":      "Evet",
    "dlg_no":       "Hayır",
    "dlg_warning":  "Uyarı",
    "dlg_error":    "Hata",
    "dlg_confirm":  "Onayla",
    "dlg_input":    "Giriş",
    "dlg_exit":     "Sunucu hala çalışıyor. Durdurup çıkılsın mı?",
    "dlg_del":      "Silinsin mi?",
    "dlg_del_article": "Bu makale silinsin mi?",
    "dlg_del_player":  "Oyuncu listeden kaldırılsın mı?",

    "browse":       "📁 Gözat",
    "no_dir":       "Dizin ayarlanmamış veya mevcut değil",
}