LANG_NAME = "中国(简体）"
LANG_CODE = "zh"

T = {
    "app_name": "CraftControl",
    "app_ready": "准备就绪。选择一个服务器然后按开始。",

    "tab_console": "⬛ 控制台",
    "tab_servers": "🖥  服务器",
    "tab_players": "👥 玩家",
    "tab_kernels": "⬇ 内核与模组",
    "tab_props":   "⚙ 属性",
    "tab_wiki":    "📖 Wiki",
    "tab_settings":"⚙ 设置",

    "toolbar_open_dir":  "📁 打开文件夹",
    "toolbar_playit":    "🌐 Playit.gg",
    "toolbar_papermc":   "📄 PaperMC",
    "status_online":     "🟢 服务器在线",
    "status_offline":    "⚫ 服务器离线",

    "console_placeholder": "输入命令... (例如：/say Hello)",
    "console_send":        "▶ 发送",
    "console_clear":       "🗑 清空",
    "console_server_offline": "服务器未运行",

    "servers_title":     "我的服务器",
    "servers_add":       "+ 添加",
    "servers_del":       "✕ 删除",
    "servers_save":      "💾 保存",
    "servers_start":     "▶ 启动",
    "servers_stop":      "⏹ 停止",
    "servers_settings":  "服务器设置",
    "servers_name":      "名称:",
    "servers_jar":       "Jar 文件:",
    "servers_dir":       "目录:",
    "servers_ram":       "内存:",
    "servers_java":      "Java:",
    "servers_port":      "端口:",
    "servers_eula":      "接受 EULA",
    "servers_eula_btn":  "创建 eula.txt",
    "servers_new_name":  "新服务器名称:",
    "servers_del_confirm": "从列表中移除此服务器？",
    "servers_eula_done": "已创建 eula.txt:",
    "servers_saved":     "服务器已保存:",
    "servers_no_jar":    "未找到 JAR 文件。请设置正确的路径。",
    "servers_starting":  "正在启动",
    "servers_stopped":   "服务器已停止",
    "servers_select":    "选择一个服务器",
    "servers_no_dir":    "请先设置服务器目录",
    "servers_rcon_group": "RCON (实时玩家列表)",
    "servers_rcon_host": "主机:",
    "servers_rcon_port": "RCON 端口:",
    "servers_rcon_pass": "RCON 密码:",
    "servers_rcon_hint": "在 server.properties 中启用：enable-rcon=true, rcon.password=...",
    "servers_api_group": "自定义服务器 API",
    "servers_api_url":   "API 地址:",
    "servers_api_key":   "API 密钥:",
    "servers_api_hint":  "用于服务器数据的 REST API。例如：http://localhost:8080",

    "players_nick":      "玩家昵称...",
    "players_add":       "+ 添加",
    "players_rank":      "角色",
    "players_status":    "状态",
    "players_ip":        "IP",
    "players_actions":   "操作",
    "players_kick":      "⚡ 踢出",
    "players_ban":       "🔨 封禁",
    "players_op":        "⭐ OP",
    "players_tp":        "🌐 传送",
    "players_online":    "在线",
    "players_offline":   "离线",
    "players_refresh":   "🔄 刷新",
    "players_added":     "玩家已添加:",
    "players_server_offline": "服务器离线。命令:",
    "players_rcon_error": "RCON 错误:",
    "players_api_error":  "API 错误:",

    "kernels_type":      "类型:",
    "kernels_fetch":     "🔍 获取列表",
    "kernels_dest":      "保存文件夹...",
    "kernels_browse":    "📁 浏览",
    "kernels_download":  "⬇ 下载内核",
    "kernels_fetching":  "正在获取列表...",
    "kernels_found":     "找到版本:",
    "kernels_none":      "未找到版本",
    "kernels_saved":     "内核已下载:",
    "kernels_select":    "从列表中选择一个版本",
    "kernels_no_dest":   "请设置保存文件夹",
    "kernels_downloading": "正在下载...",
    "kernels_error":     "下载错误:",
    "kernels_fetch_error": "获取错误:",
    "kernels_fetch_start": "正在获取内核:",

    "mods_title":        "模组 / 插件 / 数据包",
    "mods_search_ph":    "搜索... (名称或 slug)",
    "mods_search_btn":   "🔍 搜索",
    "mods_source":       "来源:",
    "mods_type":         "类型:",
    "mods_server_dir":   "服务器文件夹:",
    "mods_install":      "⬇ 安装",
    "mods_open_folder":  "📁 打开文件夹",
    "mods_installing":   "正在安装...",
    "mods_installed":    "已安装:",
    "mods_error":        "错误:",
    "mods_select":       "从列表中选择一个模组",
    "mods_no_dir":       "请设置服务器文件夹",
    "mods_searching":    "正在搜索...",
    "mods_no_results":   "未找到结果",
    "mods_results":      "结果:",

    "props_load":        "📂 加载 server.properties",
    "props_save":        "💾 保存",
    "props_saved":       "已保存:",
    "props_loaded":      "已加载:",

    "wiki_articles":     "文章",

    "settings_title":    "设置",
    "settings_ui_group": "界面",
    "settings_lang":     "语言:",
    "settings_theme":    "主题:",
    "settings_theme_dark":  "深色",
    "settings_theme_light": "浅色",
    "settings_font_size":"字体大小:",
    "settings_accent":   "强调色:",
    "settings_accent_green":  "🟢 绿色",
    "settings_accent_blue":   "🔵 蓝色",
    "settings_accent_purple": "🟣 紫色",
    "settings_accent_orange": "🟠 橙色",
    "settings_java_group": "Java",
    "settings_java_path": "Java 路径:",
    "settings_java_browse": "📁",
    "settings_java_detect": "🔍 自动检测",
    "settings_save":     "💾 保存设置",
    "settings_saved":    "设置已保存！",
    "settings_restart":  "部分更改将在重启后生效。",
    "settings_playit_group": "Playit.gg",
    "settings_playit_path": "playit.exe 的路径:",
    "settings_playit_browse": "📁",
    "settings_playit_launch": "▶ 启动 Playit",
    "settings_playit_site":   "🌐 网站",

    "dlg_ok":       "确定",
    "dlg_cancel":   "取消",
    "dlg_yes":      "是",
    "dlg_no":       "否",
    "dlg_warning":  "警告",
    "dlg_error":    "错误",
    "dlg_confirm":  "确认",
    "dlg_input":    "输入",
    "dlg_exit":     "服务器仍在运行。停止并退出？",
    "dlg_del":      "删除？",
    "dlg_del_article": "删除此文章？",
    "dlg_del_player":  "从列表中移除玩家？",

    "browse":       "📁 浏览",
    "no_dir":       "目录未设置或不存在",
}